[package]
name = "shader-patcher"
version = "0.1.0"
edition = "2021"

[dependencies]
bsdiff = "0.2.0"
clap = { version = "4.5.21", features = ["derive"] }
rfd = "0.15.1"
walkdir = "2.5.0"
zip = "2.2.1"
